version: "3.1"
services:
  postgres:
    container_name: postgres-fishcat
    image: postgres:latest
    ports:
    - "5435:5432"
    volumes:
    - pg:/data/asset
    env_file:
    - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis

volumes:
  pg: