version: "3.1"
services:
  postgres:
    container_name: postgres-fishcat
    image: postgres:latest
    ports:
    - "5435:5432"
    volumes:
    - ./data/postgres:/data/asset
    env_file:
    - .env